### ISSUE TITLE
Bularni pythonga aloqasi bormi?

### ISSUE THREAD

**Issue by Abdulhamid51** [anvarnarz/praktikum_datasets#1]
Bu file larni qaysi dasturda tuzyapsiz? Javobni comment da qoldiring iltimos.

**Comment by anvarnarz** [comment]
Bu datasetlar Data Science va Sun'iy Intellekt kursi uchun.
ai.mohirdev.uz/courses/ds

**Comment by asadbek11211** [comment]
Assalomu alaykum anvarnarz ustoz. Data Science va Sun'iy Intelekt praktikumi juda zo'r barpo qilingan. Ilmingizga ilm qo'shgay Ollohim, sizday yetuk kadir bo'lish bizga ham barcha talabalaringizga ham Nasib aylagay. Olloh rozi bo'lsin sizdan ustoz

**Comment by DataScienceShow** [comment]
Assalomu Aleykom, Tashkent house sale Uybozor saytidan webScrabing qilgan pthon scriptini bera olasizmi
,

**Comment by Abdulhamid51** [comment]
> Bu datasetlar Data Science va Sun'iy Intellekt kursi uchun. ai.mohirdev.uz/courses/ds

rahmat javob uchun mana 2 yil bo'pti endi o'qidim
